services:
  backend:
    build:
      context: ./backend
      target: production
    image: mikerutenshi/workflow-backend:latest
    platform: linux/arm64
    container_name: backend
    restart: always
    environment:
      WAIT_HOSTS: postgres:5432
    depends_on:
      - postgres
    ports:
      - 3006:3001
    networks:
      - workflow-network
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: mikerutenshi/workflow-frontend:latest
    platform: linux/arm64
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - 3005:3000
    networks:
      - workflow-network
  nginx:
    image: nginx:1.27.4-alpine
    platform: linux/arm64
    container_name: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/snippets:/etc/nginx/snippets
      - ./nginx/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro
    depends_on:
      - frontend
    networks:
      - workflow-network
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
  postgres:
    image: postgres:15.12-alpine
    platform: linux/arm64
    container_name: postgres
    networks:
      - workflow-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    volumes:
      - postgres-data:/var/lib/postgresql/data
  certbot:
    image: certbot/certbot:v4.0.0
    container_name: certbot
    platform: linux/arm64
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    # entrypoint: /bin/sh
    # command: -c "trap exit TERM; while :; do sleep 1; done"

volumes:
  postgres-data:

networks:
  workflow-network:
    driver: bridge
