services:
  backend:
    build:
      context: ./backend
      target: production
    image: mikerutenshi/workflow-backend:latest
    container_name: backend
    restart: always
    environment:
      WAIT_HOSTS: postgres:5432
    depends_on:
      - postgres
    ports:
      - 3006:3001
    networks:
      - workflow-network
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: mikerutenshi/workflow-frontend:latest
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - 3005:3000
    networks:
      - workflow-network
  nginx:
    image: nginx:1.27.4-alpine
    container_name: nginx
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/snippets:/etc/nginx/snippets
      - ./nginx/ssl/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./nginx/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
      - ./nginx/ssl/private/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    depends_on:
      - frontend
    networks:
      - workflow-network
    ports:
      - 443:443
    restart: unless-stopped
  postgres:
    image: postgres:15.12-alpine
    container_name: postgres
    networks:
      - workflow-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

networks:
  workflow-network:
    driver: bridge
