export const CACHE_PRODUCT_GROUPS = 'CACHE_PRODUCT_GROUPS';
export const CACHE_PRODUCT_GROUP = 'CACHE_PRODUCT_GROUP';
export const CACHE_PRODUCTS = 'CACHE_PRODUCTS';
export const CACHE_PRODUCT = 'CACHE_PRODUCT';
