export const Cities = [
  { id: 'Jakarta', title: 'Jakarta' },
  { id: 'Surabaya', title: 'Surabaya' },
  { id: 'Bandung', title: 'Bandung' },
  { id: 'Bekasi', title: 'Bekasi' },
  { id: 'Medan', title: 'Medan' },
  { id: 'Tangerang', title: 'Tangerang' },
  { id: 'Depok', title: 'Depok' },
  { id: 'Semarang', title: 'Semarang' },
  { id: 'Palembang', title: 'Palembang' },
  { id: 'Makassar', title: 'Makassar' },
  { id: 'SouthTangerang', title: 'Tangerang Selatan' },
  { id: 'Bogor', title: 'Bogor' },
  { id: 'Batam', title: 'Batam' },
  { id: 'Pekanbaru', title: 'Pekanbaru' },
  { id: 'BandarLampung', title: 'Bandar Lampung' },
  { id: 'Malang', title: 'Malang' },
  { id: 'Padang', title: 'Padang' },
  { id: 'Denpasar', title: 'Denpasar' },
  { id: 'Samarinda', title: 'Samarinda' },
  { id: 'Serang', title: 'Serang' },
  { id: 'Banjarmasin', title: 'Banjarmasin' },
  { id: 'Tasikmalaya', title: 'Tasikmalaya' },
  { id: 'Pontianak', title: 'Pontianak' },
  { id: 'Cimahi', title: 'Cimahi' },
  { id: 'Balikpapan', title: 'Balikpapan' },
  { id: 'Jambi', title: 'Jambi' },
  { id: 'Surakarta', title: 'Surakarta' },
  { id: 'Mataram', title: 'Mataram' },
  { id: 'Manado', title: 'Manado' },
  { id: 'Yogyakarta', title: 'Yogyakarta' },
  { id: 'Cilegon', title: 'Cilegon' },
  { id: 'Kupang', title: 'Kupang' },
  { id: 'Palu', title: 'Palu' },
  { id: 'Ambon', title: 'Ambon' },
  { id: 'Tarakan', title: 'Tarakan' },
  { id: 'Sukabumi', title: 'Sukabumi' },
  { id: 'Cirebon', title: 'Cirebon' },
  { id: 'Bengkulu', title: 'Bengkulu' },
  { id: 'Kendari', title: 'Kendari' },
  { id: 'Pekalongan', title: 'Pekalongan' },
  { id: 'Kediri', title: 'Kediri' },
  { id: 'Tegal', title: 'Tegal' },
  { id: 'Binjai', title: 'Binjai' },
  { id: 'Pematangsiantar', title: 'Pematangsiantar' },
  { id: 'Jayapura', title: 'Jayapura' },
  { id: 'BandaAceh', title: 'Banda Aceh' },
  { id: 'Palangkaraya', title: 'Palangkaraya' },
  { id: 'Probolinggo', title: 'Probolinggo' },
  { id: 'Banjarbaru', title: 'Banjarbaru' },
  { id: 'Pasuruan', title: 'Pasuruan' },
  { id: 'Tanjungpinang', title: 'Tanjungpinang' },
  { id: 'Gorontalo', title: 'Gorontalo' },
  { id: 'Dumai', title: 'Dumai' },
  { id: 'Madiun', title: 'Madiun' },
  { id: 'Batu', title: 'Batu' },
  { id: 'Salatiga', title: 'Salatiga' },
  { id: 'PangkalPinang', title: 'Pangkal Pinang' },
  { id: 'Lubuklinggau', title: 'Lubuklinggau' },
  { id: 'Ternate', title: 'Ternate' },
  { id: 'Bitung', title: 'Bitung' },
  { id: 'Tanjungbalai', title: 'Tanjungbalai' },
  { id: 'Tebingtinggi', title: 'Tebingtinggi' },
  { id: 'Metro', title: 'Metro' },
  { id: 'Bontang', title: 'Bontang' },
  { id: 'PadangSidempuan', title: 'Padang Sidempuan' },
  { id: 'Blitar', title: 'Blitar' },
  { id: 'Lhokseumawe', title: 'Lhokseumawe' },
  { id: 'Singkawang', title: 'Singkawang' },
  { id: 'Gunungsitoli', title: 'Gunungsitoli' },
  { id: 'PagarAlam', title: 'Pagar Alam' },
  { id: 'Parepare', title: 'Parepare' },
  { id: 'Langsa', title: 'Langsa' },
  { id: 'Banjar', title: 'Banjar' },
  { id: 'Prabumulih', title: 'Prabumulih' },
  { id: 'Mojokerto', title: 'Mojokerto' },
  { id: 'Magelang', title: 'Magelang' },
  { id: 'Sorong', title: 'Sorong' },
  { id: 'Payakumbuh', title: 'Payakumbuh' },
  { id: 'Palopo', title: 'Palopo' },
  { id: 'Bima', title: 'Bima' },
  { id: 'Bukittinggi', title: 'Bukittinggi' },
  { id: 'Kotamobagu', title: 'Kotamobagu' },
  { id: 'BauBau', title: 'Bau-Bau' },
  { id: 'Tomohon', title: 'Tomohon' },
  { id: 'TidoreKepulauan', title: 'Tidore Kepulauan' },
  { id: 'Sibolga', title: 'Sibolga' },
  { id: 'Sungaipenuh', title: 'Sungaipenuh' },
  { id: 'Pariaman', title: 'Pariaman' },
  { id: 'Subulussalam', title: 'Subulussalam' },
  { id: 'Solok', title: 'Solok' },
  { id: 'Tual', title: 'Tual' },
  { id: 'Sawahlunto', title: 'Sawahlunto' },
  { id: 'PadangPanjang', title: 'Padang Panjang' },
  { id: 'Sabang', title: 'Sabang' },
];
