export const Provinces = [
  { id: 'Aceh', title: 'Nanggroe Aceh Darussalam' },
  { id: 'NorthSumatra', title: 'Sumatera Utara' },
  { id: 'SouthSumatra', title: 'Sumatera Selatan' },
  { id: 'WestSumatra', title: 'Sumatera Barat' },
  { id: 'Bengkulu', title: 'Bengkulu' },
  { id: 'Riau', title: 'Riau' },
  { id: 'RiauIslands', title: 'Kepulauan Riau' },
  { id: 'Jambi', title: 'Jambi' },
  { id: 'Lampung', title: 'Lampung' },
  { id: 'BangkaBelitung', title: 'Bangka Belitung' },
  { id: 'WestKalimantan', title: 'Kalimantan Barat' },
  { id: 'EastKalimantan', title: 'Kalimantan Timur' },
  { id: 'SouthKalimantan', title: 'Kalimantan Selatan' },
  { id: 'CentralKalimantan', title: 'Kalimantan Tengah' },
  { id: 'NorthKalimantan', title: 'Kalimantan Utara' },
  { id: 'Banten', title: 'Banten' },
  { id: 'Jakarta', title: 'DKI Jakarta' },
  { id: 'WestJava', title: 'Jawa Barat' },
  { id: 'CentralJava', title: 'Jawa Tengah' },
  { id: 'Yogyakarta', title: 'Daerah Istimewa Yogyakarta' },
  { id: 'EastJava', title: 'Jawa Timur' },
  { id: 'Bali', title: 'Bali' },
  { id: 'EastNusaTenggara', title: 'Nusa Tenggara Timur' },
  { id: 'WestNusaTenggara', title: 'Nusa Tenggara Barat' },
  { id: 'Gorontalo', title: 'Gorontalo' },
  { id: 'WestSulawesi', title: 'Sulawesi Barat' },
  { id: 'CentralSulawesi', title: 'Sulawesi Tengah' },
  { id: 'NorthSulawesi', title: 'Sulawesi Utara' },
  { id: 'SoutheastSulawesi', title: 'Sulawesi Tenggara' },
  { id: 'SouthSulawesi', title: 'Sulawesi Selatan' },
  { id: 'NorthMaluku', title: 'Maluku Utara' },
  { id: 'Maluku', title: 'Maluku' },
  { id: 'WestPapua', title: 'Papua Barat' },
  { id: 'Papua', title: 'Papua' },
  { id: 'CentralPapua', title: 'Papua Tengah' },
  { id: 'HighlandPapua', title: 'Papua Pegunungan' },
  { id: 'SouthPapua', title: 'Papua Selatan' },
  { id: 'SouthwestPapua', title: 'Papua Barat Daya' },
];
