fragment AuthUser on User {
  id
  email
  firstName
  lastName
}

mutation signIn($data: SignInDto!) {
  signIn(data: $data) {
    ...AuthUser
  }
}

mutation signOut {
  signOut {
    ...AuthUser
  }
}

query me {
  me {
    ...AuthUser
  }
}
