fragment AuthUser on User {
  id
  email
  firstName
  lastName
  createdAt
  role {
    name
    clearanceLevel
  }
}

mutation logIn($data: LogInDto!) {
  logIn(data: $data) {
    ...AuthUser
  }
}

mutation logOut {
  logOut {
    ...AuthUser
  }
}

query me {
  me {
    ...AuthUser
  }
}

query getUsers {
  getUsers {
    ...AuthUser
  }
}
