fragment AuthUser on User {
  id
  email
  firstName
  lastName
}

mutation logIn($data: LogInDto!) {
  logIn(data: $data) {
    ...AuthUser
  }
}

mutation logOut {
  logOut {
    ...AuthUser
  }
}

query me {
  me {
    ...AuthUser
  }
}

query getUsers {
  getUsers {
    id
    email
    firstName
    lastName
    createdAt
    role {
      name
    }
  }
}
