fragment Inventory on Inventory {
  id
  name
  address
  city
  province
  type
}

mutation createInventory($data: InventoryCreateDto!) {
  createInventory(data: $data) {
    id
  }
}

query getInventories {
  getInventories {
    ...Inventory
  }
}

query getInventory($id: ID!) {
  getInventory(id: $id) {
    ...Inventory
  }
}

mutation updateInventory($id: ID!, $data: InventoryUpdateDto!) {
  updateInventory(id: $id, data: $data) {
    id
  }
}

mutation deleteInventory($id: ID!) {
  deleteInventory(id: $id)
}

mutation createInvProduct($data: InvProductCreateDto!) {
  createInvProduct(data: $data) {
    id
  }
}

query getInvProducts {
  getInvProducts {
    id
    invId
    productId
    product {
      id
      sku
      productGroup {
        id
        name
        productCategory {
          ...ProductCategory
        }
      }
      productColors {
        color {
          ...Color
        }
      }
    }
    invProductSizes {
      size {
        ...Size
      }
      quantity
    }
    sellingPrice
    discount
  }
}

mutation updateINvProduct($id: ID!, $data: InvProductUpdateDto!) {
  updateInvProduct(id: $id, data: $data) {
    id
  }
}

mutation deleteInvProduct($id: ID!) {
  deleteInvProduct(id: $id)
}
