fragment ProductCategoryFrag on ProductCategory {
  id
  name
  gender
}

fragment ColorFrag on Color {
  id
  name
  hexCode
}

fragment LaborCostFrag on LaborCost {
  id
  drawingUpper
  drawingLining
  stitchingUpper
  stitchingInsole
  stitchingOutsole
  lasting
  createdBy
  createdAt
  updatedBy
  updatedAt
}

mutation createPrdouctCategory($data: CreateProductCategoryDto!) {
  createProductCategory(data: $data) {
    ...ProductCategoryFrag
  }
}

mutation createProductGroup($data: CreateProductGroupDto!) {
  createProductGroup(data: $data) {
    id
    skuNumeric
    name
    productCategoryId
  }
}

mutation createColor($data: CreateColorDto!) {
  createColor(data: $data) {
    ...ColorFrag
  }
}

mutation createProduct($data: CreateProductDto!) {
  createProduct(data: $data) {
    id
  }
}

mutation updateProduct($id: ID!, $data: CreateProductDto!) {
  updateProduct(id: $id, data: $data) {
    id
  }
}

mutation deleteProduct($id: ID!) {
  deleteProduct(id: $id)
}

mutation createLaborCost($data: CreateLaborCostDto!) {
  createLaborCost(data: $data) {
    id
  }
}

mutation updateLaborCost($id: ID!, $data: CreateLaborCostDto!) {
  updateLaborCost(id: $id, data: $data) {
    id
  }
}

query getProductCategories {
  getProductCategories {
    ...ProductCategoryFrag
  }
}

query getColors {
  getColors {
    ...ColorFrag
  }
}

query getProductGroups {
  getProductGroups {
    id
    skuNumeric
    name
    productCategory {
      ...ProductCategoryFrag
    }
    laborCost {
      ...LaborCostFrag
    }
  }
}

query getProductGroup($id: ID!) {
  getProductGroup(id: $id) {
    id
    skuNumeric
    name
    productCategory {
      ...ProductCategoryFrag
    }
    laborCost {
      ...LaborCostFrag
    }
  }
}

query getProducts {
  getProducts {
    id
    sku
    productGroup {
      id
      skuNumeric
      productCategory {
        ...ProductCategoryFrag
      }
    }
    productColors {
      order
      color {
        ...ColorFrag
      }
    }
  }
}

query getProduct($id: ID!) {
  getProduct(id: $id) {
    id
    sku
    productGroup {
      id
    }
    productColors {
      order
      color {
        id
      }
    }
  }
}
