fragment ProductCategory on ProductCategory {
  id
  name
  gender
}

fragment Color on Color {
  id
  name
  hexCode
}

fragment LaborCost on LaborCost {
  id
  type
  cost
  createdBy
  createdAt
  updatedBy
  updatedAt
}

mutation createPrdouctCategory($data: ProductCategoryCreateDto!) {
  createProductCategory(data: $data) {
    ...ProductCategory
  }
}
mutation updateProductCategory($id: ID!, $data: ProductCategoryCreateDto!) {
  updateProductCategory(id: $id, data: $data) {
    id
  }
}
mutation deleteProductCategory($id: ID!) {
  deleteProductCategory(id: $id)
}

mutation createProductGroup($data: ProductGroupCreateDto!) {
  createProductGroup(data: $data) {
    id
    skuNumeric
    name
    productCategoryId
  }
}
mutation updateProductGroup($id: ID!, $data: ProductGroupCreateDto!) {
  updateProductGroup(id: $id, data: $data) {
    id
  }
}
mutation deleteProductGroup($id: ID!) {
  deleteProductGroup(id: $id)
}

mutation createColor($data: ColorCreateDto!) {
  createColor(data: $data) {
    ...Color
  }
}

mutation updateColor($id: ID!, $data: ColorCreateDto!) {
  updateColor(id: $id, data: $data) {
    id
  }
}

mutation deleteColor($id: ID!) {
  deleteColor(id: $id)
}

mutation createProduct($data: ProductCreateDto!) {
  createProduct(data: $data) {
    id
  }
}

mutation updateProduct($id: ID!, $data: ProductUpdateDto!) {
  updateProduct(id: $id, data: $data) {
    id
  }
}

mutation deleteProduct($id: ID!) {
  deleteProduct(id: $id)
}

mutation upsertLaborCosts($productGroupId: ID!, $data: [LaborCostUpsertDto!]!) {
  upsertLaborCosts(productGroupId: $productGroupId, data: $data) {
    id
  }
}

mutation updateLaborCosts($data: LaborCostUpdateDto!) {
  updateLaborCosts(data: $data)
}

query getProductCategories {
  getProductCategories {
    ...ProductCategory
  }
}
query getProductCategory($id: ID!) {
  getProductCategory(id: $id) {
    ...ProductCategory
  }
}

query getColors {
  getColors {
    ...Color
  }
}

query getColor($id: ID!) {
  getColor(id: $id) {
    ...Color
  }
}

query getProductGroups {
  getProductGroups {
    id
    skuNumeric
    name
    productCategory {
      ...ProductCategory
    }
  }
}

query getProductGroup($id: ID!) {
  getProductGroup(id: $id) {
    id
    skuNumeric
    name
    productCategory {
      ...ProductCategory
    }
    createdBy
    updatedBy
  }
}

query getProducts {
  getProducts {
    id
    sku
    productGroup {
      id
      skuNumeric
      productCategory {
        ...ProductCategory
      }
      name
      msrp
    }
    productColors {
      order
      color {
        ...Color
      }
    }
  }
}

query getProduct($id: ID!) {
  getProduct(id: $id) {
    id
    sku
    productGroup {
      id
      msrp
    }
    productColors {
      order
      color {
        id
      }
    }
    createdBy
    updatedBy
  }
}

query getLaborCost($id: ID!) {
  getLaborCost(id: $id) {
    id
    skuNumeric
    name
    productCategory {
      ...ProductCategory
    }
    laborCosts {
      ...LaborCost
    }
  }
}

query getLaborCosts {
  getLaborCosts {
    id
    skuNumeric
    name
    productCategory {
      ...ProductCategory
    }
    laborCosts {
      ...LaborCost
    }
  }
}
