fragment SaleFragment on Sale {
  id
  date
  saleNo
  saleItems {
    id
    saleItemSizes {
      quantity
      size {
        ...Size
      }
    }
  }
}
mutation createSale($data: SaleCreateDto!) {
  createSale(data: $data) {
    id
  }
}

query getSales {
  getSales {
    ...SaleFragment
  }
}

query generateSaleNo {
  generateSaleNo
}
