import { Field, ID, InputType } from '@nestjs/graphql';
import { Transform, Type } from 'class-transformer';
import {
  ArrayNotEmpty,
  IsArray,
  IsDate,
  IsOptional,
  IsString,
  Matches,
  MaxLength,
  Min,
  ValidateNested,
} from 'class-validator';
import { SizeToWorkCreateDto } from './size-to-work-create.dto';

// The actor is taken from the authenticated context, never from the payload,
// so a client cannot claim to have acted as someone else.
@InputType()
export class WorkCreateDto {
  @Field(() => Date)
  @IsDate()
  date!: Date;

  // Two issuers share this field: WRK-250801-0001 generated by
  // WorkService.generateOrderNo, or a plain number typed in from the
  // external system. Mirrors orderNoSchema in
  // frontend/app/validation/schema.ts -- keep the two in sync.
  @Field()
  @Matches(/^([A-Z]{2,3}-[0-9]{6}-[0-9]{4}|[0-9]+)$/, {
    message: 'Format support example: WRK-250801-0001 or 26080001',
  })
  orderNo!: string;

  @Field(() => ID)
  @Transform(({ value }) => parseInt(value, 10))
  @Min(1)
  productId!: number;

  @Field(() => [SizeToWorkCreateDto])
  @Type(() => SizeToWorkCreateDto)
  @ValidateNested({ each: true })
  @ArrayNotEmpty()
  workSizes!: SizeToWorkCreateDto[];

  @Field(() => String, { nullable: true })
  @IsString()
  @MaxLength(255)
  @IsOptional()
  note!: string | null;

  // Empty is allowed -- not every run is spoken for. GraphQL delivers ID as a
  // string, hence the parse, matching invIds in auth/dto/user-update.dto.ts.
  @Field(() => [ID])
  @Transform(({ value }) => value.map((member: any) => parseInt(member, 10)))
  @IsArray()
  @Min(1, { each: true })
  tagIds!: number[];
}
