fragment AuthUser on User {
  id
  email
  firstName
  lastName
  createdAt
  updatedAt
  role {
    id
    name
    clearanceLevel
  }
  userInventories {
    id
    name
  }
  isActive
}
mutation createUser($data: UserCreateDto!) {
  createUser(data: $data) {
    ...AuthUser
  }
}

mutation logIn($data: LogInDto!) {
  logIn(data: $data) {
    ...AuthUser
  }
}

mutation logOut {
  logOut {
    ...AuthUser
  }
}

mutation updateUser($id: ID!, $data: UserUpdateDto!) {
  updateUser(id: $id, data: $data) {
    id
  }
}

mutation verifyHuman($token: String!) {
  verifyHuman(token: $token)
}

query me {
  me {
    ...AuthUser
  }
}

query getUsers {
  getUsers {
    ...AuthUser
  }
}

query getRoles {
  getRoles {
    id
    name
    description
    clearanceLevel
  }
}
