fragment InventoryFragment on InventoryDto {
  id
  name
  address
  city
  province
  type
  priceFormula {
    id
    offset
    multiplier
    profitMargins
  }
}

mutation createInventory($data: InventoryCreateDto!) {
  createInventory(data: $data) {
    id
  }
}

query getInventories {
  getInventories {
    ...InventoryFragment
  }
}

query getInventory($id: ID!) {
  getInventory(id: $id) {
    ...InventoryFragment
  }
}

mutation updateInventory($id: ID!, $data: InventoryUpdateDto!) {
  updateInventory(id: $id, data: $data) {
    id
  }
}

mutation deleteInventory($id: ID!) {
  deleteInventory(id: $id)
}

mutation createInvProduct($data: InvProductCreateDto!) {
  createInvProduct(data: $data) {
    invId
    productId
  }
}

query getInvProducts($invId: ID!) {
  getInvProducts(invId: $invId) {
    invId
    productId
    product {
      id
      sku
      productGroup {
        id
        name
        productCategory {
          ...ProductCategory
        }
      }
      productColors {
        color {
          ...Color
        }
      }
    }
    invProductSizes {
      size {
        ...Size
      }
      quantity
    }
    invTrfItems {
      progress
      invTrfItemSizes {
        size {
          ...Size
        }
        quantity
      }
      invTrf {
        id
        trfNo
      }
    }
    discounts
    price
  }
}

mutation updateInvProduct(
  $invId: ID!
  $productId: ID!
  $data: InvProductUpdateDto!
) {
  updateInvProduct(invId: $invId, productId: $productId, data: $data) {
    invId
    productId
  }
}

mutation updateInvProductDisc($data: InvProductUpdateDiscDto!) {
  updateInvProductDisc(data: $data) {
    invId
    productId
    discounts
  }
}

mutation deleteInvProduct($invId: ID!, $productId: ID!) {
  deleteInvProduct(invId: $invId, productId: $productId)
}

mutation uploadNewInvProducts($data: CsvUploadDto!) {
  uploadNewInvProducts(data: $data)
}

mutation uploadInvProductDiscounts($data: CsvUploadDto!) {
  uploadInvProductDiscounts(data: $data)
}

query getInvTrfItemTrfs($invId: ID!, $productId: ID!) {
  getInvTrfItemTrfs(invId: $invId, productId: $productId) {
    id
    fromInv {
      name
      type
    }
    toInv {
      name
      type
    }
    productId
    progress
    invTrfItemSizes {
      size {
        ...Size
      }
      quantity
    }
    invTrf {
      id
      trfNo
      trfDate
      progress
    }
  }
}

query getInvTrfItems($fromInvId: ID!, $toInvId: ID!, $progress: [Progress!]) {
  getInvTrfItems(
    fromInvId: $fromInvId
    toInvId: $toInvId
    progress: $progress
  ) {
    id
    fromInv {
      id
      name
      type
    }
    toInv {
      id
      name
      type
    }
    product {
      id
      sku
    }
    price
    discounts
    progress
    invTrfItemSizes {
      size {
        ...Size
      }
      quantity
    }
    invTrf {
      id
    }
  }
}

query getInvTrfs {
  getInvTrfs {
    id
    trfNo
    work {
      id
      orderNo
    }
    fromInv {
      id
      name
      type
    }
    toInv {
      id
      name
      type
    }
    trfDate
    progress
  }
}

query getInvTrf($id: ID!) {
  getInvTrf(id: $id) {
    id
    trfNo
    fromInv {
      id
      name
      address
      city
      province
      type
    }
    toInv {
      id
      name
      address
      city
      province
      type
      priceFormula {
        profitMargins
      }
    }
    trfDate
    progress
    note
    invTrfItems {
      id
      product {
        id
        sku
      }
      fromInv {
        id
        name
        type
      }
      toInv {
        id
        name
        type
      }
      price
      discounts
      progress
      invTrfItemSizes {
        invTrfItemId
        size {
          ...Size
        }
        quantity
      }
    }
  }
}

mutation createInvTrf($data: InvTrfCreateDto!) {
  createInvTrf(data: $data) {
    id
  }
}

mutation updateInvTrf($id: ID!, $data: InvTrfUpdateDto!) {
  updateInvTrf(id: $id, data: $data) {
    id
  }
}

# mutation updateInvTrfProgress($id: ID!, $data: InvTrfUpdateProgressDto!) {
#   updateInvTrfProgress(id: $id, data: $data)
# }

mutation deleteInvTrf($id: ID!) {
  deleteInvTrf(id: $id)
}

mutation createInvTrfItem($data: InvTrfItemCreateDto!) {
  createInvTrfItem(data: $data) {
    id
  }
}

mutation deleteInvTrfItem($id: ID!) {
  deleteInvTrfItem(id: $id)
}

query generateInvTrfNo($date: Date!) {
  generateInvTrfNo(date: $date)
}

query getInvTxs($invId: ID!, $productId: ID!) {
  getInvTxs(invId: $invId, productId: $productId) {
    id
    type
    saleId
    trfId
    adjId
    invTxSizes {
      size {
        ...Size
      }
      quantity
    }
    txNo
    txDate
    progress
  }
}

query getInvProductPrice($invId: ID!, $productId: ID!, $discounts: [String!]!) {
  getInvProductPrice(
    invId: $invId
    productId: $productId
    discounts: $discounts
  )
}

query downloadInvProducts {
  downloadInvProducts
}

query getInvAdjs($invId: ID) {
  getInvAdjs(invId: $invId) {
    id
    adjNo
    adjDate
    progress
    note
    itemCount
    totalVariance
    inventory {
      id
      name
      type
    }
  }
}

query getInvAdj($id: ID!) {
  getInvAdj(id: $id) {
    id
    adjNo
    adjDate
    progress
    note
    invId
    inventory {
      id
      name
      type
    }
    invAdjItems {
      id
      productId
      reason
      note
      product {
        id
        sku
      }
      invAdjItemSizes {
        size {
          ...Size
        }
        systemQty
        countedQty
      }
    }
  }
}

query generateInvAdjNo($date: Date!) {
  generateInvAdjNo(date: $date)
}

mutation createInvAdj($data: InvAdjCreateDto!) {
  createInvAdj(data: $data) {
    id
  }
}

mutation updateInvAdj($id: ID!, $data: InvAdjUpdateDto!) {
  updateInvAdj(id: $id, data: $data) {
    id
  }
}

mutation postInvAdj($id: ID!) {
  postInvAdj(id: $id) {
    id
    progress
  }
}

mutation deleteInvAdj($id: ID!) {
  deleteInvAdj(id: $id)
}
