fragment InventoryFragment on InventoryDto {
  id
  name
  address
  city
  province
  type
  priceFormula {
    id
    offset
    multiplier
    discounts
  }
}

mutation createInventory($data: InventoryCreateDto!) {
  createInventory(data: $data) {
    id
  }
}

query getInventories {
  getInventories {
    ...InventoryFragment
  }
}

query getInventory($id: ID!) {
  getInventory(id: $id) {
    ...InventoryFragment
  }
}

mutation updateInventory($id: ID!, $data: InventoryUpdateDto!) {
  updateInventory(id: $id, data: $data) {
    id
  }
}

mutation deleteInventory($id: ID!) {
  deleteInventory(id: $id)
}

mutation createInvProduct($data: InvProductCreateDto!) {
  createInvProduct(data: $data) {
    invId
    productId
  }
}

query getInvProducts($invId: ID!) {
  getInvProducts(invId: $invId) {
    invId
    productId
    product {
      id
      sku
      productGroup {
        id
        name
        productCategory {
          ...ProductCategory
        }
        msrp
      }
      productColors {
        color {
          ...Color
        }
      }
    }
    invProductSizes {
      size {
        ...Size
      }
      quantity
    }
    invTrfItems {
      progress
      invTrfItemSizes {
        size {
          ...Size
        }
        quantity
      }
    }
    discounts
    price
  }
}

mutation updateInvProduct(
  $invId: ID!
  $productId: ID!
  $data: InvProductUpdateDto!
) {
  updateInvProduct(invId: $invId, productId: $productId, data: $data) {
    invId
    productId
  }
}

mutation updateInvProductDisc($data: InvProductUpdateDiscDto!) {
  updateInvProductDisc(data: $data) {
    invId
    productId
    discounts
  }
}

mutation deleteInvProduct($invId: ID!, $productId: ID!) {
  deleteInvProduct(invId: $invId, productId: $productId)
}

query getInvTrfItemTrfs($invId: ID!, $productId: ID!) {
  getInvTrfItemTrfs(invId: $invId, productId: $productId) {
    id
    fromInv {
      name
      type
    }
    toInv {
      name
      type
    }
    productId
    progress
    invTrfItemSizes {
      size {
        ...Size
      }
      quantity
    }
    invTrf {
      id
      trfNo
      trfDate
      progress
    }
  }
}

query getInvTrfItems($fromInvId: ID!, $toInvId: ID!, $progress: Progress) {
  getInvTrfItems(
    fromInvId: $fromInvId
    toInvId: $toInvId
    progress: $progress
  ) {
    id
    fromInv {
      id
      name
      type
    }
    toInv {
      id
      name
      type
    }
    product {
      id
      sku
      productGroup {
        id
        skuNumeric
        msrp
      }
    }
    discounts
    progress
    invTrfItemSizes {
      size {
        ...Size
      }
      quantity
    }
    invTrf {
      id
    }
  }
}

query getInvTrfs {
  getInvTrfs {
    id
    trfNo
    work {
      id
      orderNo
    }
    fromInv {
      id
      name
      type
    }
    toInv {
      id
      name
      type
    }
    trfDate
    progress
  }
}

query getInvTrf($id: ID!) {
  getInvTrf(id: $id) {
    id
    trfNo
    fromInv {
      id
      name
      address
      city
      province
      type
    }
    toInv {
      id
      name
      address
      city
      province
      type
    }
    trfDate
    progress
    invTrfItems {
      id
      product {
        id
        sku
        productGroup {
          id
          skuNumeric
          msrp
        }
      }
      fromInv {
        id
        name
        type
      }
      toInv {
        id
        name
        type
      }
      discounts
      progress
      invTrfItemSizes {
        invTrfItemId
        size {
          ...Size
        }
        quantity
      }
    }
  }
}

mutation createInvTrf($data: InvTrfCreateDto!) {
  createInvTrf(data: $data) {
    id
  }
}

mutation updateInvTrf($id: ID!, $data: InvTrfUpdateDto!) {
  updateInvTrf(id: $id, data: $data) {
    id
  }
}

mutation deleteInvTrf($id: ID!) {
  deleteInvTrf(id: $id)
}

mutation createInvTrfItem($data: InvTrfItemCreateDto!) {
  createInvTrfItem(data: $data) {
    id
  }
}

mutation deleteInvTrfItem($id: ID!) {
  deleteInvTrfItem(id: $id)
}

query generateInvTrfNo {
  generateInvTrfNo
}

query getInvTxs($invId: ID!, $productId: ID!) {
  getInvTxs(invId: $invId, productId: $productId) {
    id
    type
    saleId
    trfId
    invTxSizes {
      size {
        ...Size
      }
      quantity
    }
    txNo
    txDate
    progress
  }
}
