fragment Tag on Tag {
  id
  name
  archived
}

fragment Size on Size {
  id
  eu
  us
  uk
  jp
  gender
}

fragment TaskAndArtisan on TaskAndArtisanDto {
  id
  createdBy
  createdAt
  updatedBy
  updatedAt
  workId
  type
  artisan {
    id
    firstName
    lastName
    jobs
    createdBy
    updatedBy
  }
  doneAt
}

fragment WorkAndTasks on WorkAndTasksDto {
  id
  date
  orderNo
  productId
  workSizes {
    size {
      ...Size
    }
    quantity
  }
  tags {
    ...Tag
  }
  tasks {
    ...TaskAndArtisan
  }
  product {
    sku
    productGroup {
      skuNumeric
    }
  }
  progress
  note
  invTrf {
    trfNo
  }
  createdBy
  updatedBy
  createdAt
  updatedAt
}

fragment Work on WorkAndTasksDto {
  id
  date
  orderNo
  productId
  workSizes {
    size {
      ...Size
    }
    quantity
  }
  tags {
    ...Tag
  }
  product {
    sku
  }
  note
  createdBy
  updatedBy
}

mutation createTag($data: TagCreateDto!) {
  createTag(data: $data) {
    ...Tag
  }
}

mutation updateTag($id: ID!, $data: TagCreateDto!) {
  updateTag(id: $id, data: $data) {
    ...Tag
  }
}

mutation deleteTag($id: ID!) {
  deleteTag(id: $id)
}

query getTags {
  getTags {
    ...Tag
  }
}

query getTag($id: ID!) {
  getTag(id: $id) {
    ...Tag
  }
}

mutation createSize($data: SizeCreateDto!) {
  createSize(data: $data) {
    id
  }
}

mutation updateSize($id: ID!, $data: SizeCreateDto!) {
  updateSize(id: $id, data: $data) {
    id
  }
}

mutation deleteSize($id: ID!) {
  deleteSize(id: $id)
}

query getSizes {
  getSizes {
    ...Size
  }
}

query getSize($id: ID!) {
  getSize(id: $id) {
    ...Size
  }
}

mutation createWork($data: WorkCreateDto!) {
  createWork(data: $data) {
    id
  }
}

mutation updateWork($id: ID!, $data: WorkUpdateDto!) {
  updateWork(id: $id, data: $data) {
    id
  }
}

mutation deleteWork($id: ID!) {
  deleteWork(id: $id)
}

query getWorks($startDate: Date!, $endDate: Date!) {
  getWorks(startDate: $startDate, endDate: $endDate) {
    ...WorkAndTasks
  }
}

query getWork($id: ID!) {
  getWork(id: $id) {
    ...Work
  }
}

query getTasks($workId: ID!) {
  getTasks(workId: $workId) {
    ...TaskAndArtisan
  }
}

mutation updateTasks($data: [TaskUpdateDto!]!) {
  updateTasks(data: $data) {
    id
  }
}

mutation addToInventory($data: AddToInventoryDto!) {
  addToInventory(data: $data)
}

query getPayroll($startDate: Date!, $endDate: Date!) {
  getPayroll(startDate: $startDate, endDate: $endDate) {
    artisans {
      id
      firstName
      lastName
      jobs
      tasks {
        payablePerTask
        costPerTask
        quantityPerTask
        type
        doneAt
        work {
          orderNo
          workSizes {
            size {
              eu
            }
            quantity
          }
          product {
            id
            sku
            productGroup {
              id
              skuNumeric
              productCategory {
                id
                name
              }
            }
          }
        }
      }
      payablePerArtisan
      quantityPerArtisan
    }
    totalPayable
    totalQuantity
  }
}

query generateOrderNo($date: Date!) {
  generateOrderNo(date: $date)
}

query getWorkAuditTrail($id: ID!) {
  getWork(id: $id) {
    date
    createdAt
    updatedAt
    createdBy
    updatedBy
  }
}
