fragment SaleFragment on Sale {
  id
  date
  saleNo
  saleItems {
    id
    productId
    saleItemSizes {
      quantity
      size {
        ...Size
      }
    }
  }
}
mutation createSale($data: SaleCreateDto!) {
  createSale(data: $data) {
    id
  }
}

mutation updateSale($id: ID!, $data: SaleUpdateDto!) {
  updateSale(id: $id, data: $data) {
    id
  }
}

query getSales($invId: ID) {
  getSales(invId: $invId) {
    ...SaleFragment
  }
}

query getSale($id: ID!) {
  getSale(id: $id) {
    ...SaleFragment
  }
}

query generateSaleNo {
  generateSaleNo
}

mutation deleteSale($id: ID!) {
  deleteSale(id: $id)
}
