fragment SaleFragment on SaleDto {
  id
  date
  saleNo
  saleItems {
    id
    productId
    invId
    inventory {
      id
      name
    }
    saleItemSizes {
      quantity
      size {
        ...Size
      }
    }
  }
}
mutation createSale($data: SaleCreateDto!) {
  createSale(data: $data) {
    id
  }
}

mutation updateSale($id: ID!, $data: SaleUpdateDto!) {
  updateSale(id: $id, data: $data) {
    id
  }
}

query getSales($invId: ID, $startDate: Date, $endDate: Date) {
  getSales(invId: $invId, startDate: $startDate, endDate: $endDate) {
    ...SaleFragment
  }
}

query getSale($id: ID!) {
  getSale(id: $id) {
    ...SaleFragment
  }
}

query generateSaleNo($date: Date!) {
  generateSaleNo(date: $date)
}

mutation deleteSale($id: ID!) {
  deleteSale(id: $id)
}

query getSalePerformance($startDate: Date!, $endDate: Date!, $invId: ID) {
  getSalePerformance(startDate: $startDate, endDate: $endDate, invId: $invId) {
    productId
    sku
    productGroupName
    productCategoryName
    gender
    totalQuantity
  }
}
